name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  rust:
    strategy:
      matrix:
        toolchain: [stable, beta, nightly]
    name: Rust
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          profile: minimal
          override: true
          toolchain: ${{ matrix.toolchain }}
      - run: cargo build
      - run: cargo test

